[package]
name = "aoc2021"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10"
tap = "1.0"
bitvec = "0.22"
